---
title: "Automatización Datacamp"
output:
  html_document: default
  pdf_document: default
date: "2026-04-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Librerias
library(readxl)
library(writexl)
library(stringr)
library(dplyr)
```

```{r}
archivo_zip <- "2025-26 Tractament de les dades Gr.A-T (36423)-Tarea Intermediate R(Datacamp)-3281647.zip"

unzip(archivo_zip, exdir = "entregas")

ficheros_puntos <- list.files("entregas", pattern = "\\.txt$", recursive = TRUE, full.names = TRUE)
ficheros_justificantes <- list.files("entregas", pattern = "justificante|certificate.*\\.(pdf|png|jpg)$", recursive = TRUE, full.names = TRUE)

lista_resultados <- lapply(ficheros_puntos,function(ruta) {
  partes <- unlist(strsplit(ruta, split = "/"))
  carpeta_alumno <- partes[length(partes) - 1]  
  apellido_solo <- unlist(strsplit(carpeta_alumno, split = "_"))[1]                 
  lineas <- readLines(ruta, warn = FALSE)        
  
texto_limpio <- str_replace_all(lineas, "\\.", "")
nota_num <- as.numeric(str_extract(texto_limpio, "\\d+"))
  data.frame(
    "Apellido(s)" = apellido_solo,
    "puntos" = nota_num,
    "NomFile" = basename(ruta),
    "Puntos" = paste(lineas, collapse = " "), 
    stringsAsFactors = FALSE,
    check.names = FALSE
  )})




```
```{r}
evalua_df <- do.call(rbind, lista_resultados) %>%
  group_by(`Apellido(s)`) %>%
  filter(puntos == max(puntos, na.rm = TRUE)) %>%
  slice(1) %>% 
  ungroup()

evalua_df <- evalua_df %>%
  mutate(`Apellido(s)` = str_remove(`Apellido(s)`, ",.*$"),
         `Apellido(s)` = str_trim(`Apellido(s)`))

alumnos_matriculados <- read_excel("AlumnosTD25_26.xlsx") %>%
  mutate(`Apellido(s)` = str_trim(`Apellido(s)`))

alumnos_notas_final <- left_join(alumnos_matriculados, evalua_df, by = "Apellido(s)")
alumnos_notas_final <- alumnos_notas_final %>%
  arrange(`Apellido(s)`)

write_xlsx(evalua_df, "NotasRIntermedio.xlsx")
write_xlsx(alumnos_notas_final, "AlumnosNotas.xlsx")
```



